version: '2.4'
services:
  ziti-controller:
    image: netfoundry/ziti-quickstart
    build: ./image
    ports:
      - 1280:1280
    networks:
      ziticontrol:
        aliases:
          - ziti-controller
          - ziti-edge-controller
    volumes:
      - ziti-fs:/netfoundry
    entrypoint:
      - /home/ziti/run-controller.sh

  ziti-edge-router:
    image: netfoundry/ziti-quickstart
    depends_on:
      ziti-controller:
        condition: service_started
    ports:
      - 3022:3022
    networks:
      ziticontrol:
        aliases:
          - ziti-edge-router
            #entrypoint:
            #  - /home/ziti/run-edge-router.sh

    command: ["wait-for-it", "ziti-controller:1280", "-t", "120", "--", "./run-edge-router.sh"]
    volumes:
      - ziti-fs:/netfoundry


networks:
  ziticontrol:
  zitired:
  zitiblue:

volumes:
  ziti-fs:

