version: '2.4'
services:
  ziti-controller:
    image: openziti/ziti-quickstart
    build: ./image
    ports:
      - 1280:1280
    networks:
      ziticontrol:
        aliases:
          - ziti-controller
          - ziti-edge-controller
    volumes:
      - ziti-fs:/openziti
    entrypoint:
      - /openziti/run-controller.sh

  ziti-edge-router:
    image: openziti/ziti-quickstart
    depends_on:
      ziti-controller:
        condition: service_started
    ports:
      - 3022:3022
    networks:
      ziticontrol:
        aliases:
          - ziti-edge-router
    volumes:
      - ziti-fs:/openziti
    entrypoint:
      - /openziti/run-edge-router.sh
    #command: ["wait-for-it", "ziti-controller:1280", "-t", "120", "--", "./run-edge-router.sh"]

networks:
  ziticontrol:
  zitired:
  zitiblue:

volumes:
  ziti-fs:


