version: '2.4'
services:
  ziti-controller:
    image: openziti/ziti-quickstart
    env_file:
      - ./default.env
    build: ./image
    ports:
      - 1280:1280
    networks:
      ziticontrol:
        aliases:
          - ziti-edge-controller
    volumes:
      - ziti-fs:/openziti
    entrypoint:
      - /openziti/run-controller.sh

  ziti-edge-router:
    image: openziti/ziti-quickstart
    environment:
      - ZITI_EDGE_ROUTER_RAWNAME=ziti-edge-router
    ports:
      - 3022:3022
    networks:
      - ziticontrol
    volumes:
      - ziti-fs:/openziti
    entrypoint: /bin/bash
    command: "/openziti/run-edge-router.sh edge"

  ziti-edge-router-wss:
    image: openziti/ziti-quickstart
    environment:
      - ZITI_EDGE_ROUTER_RAWNAME=ziti-edge-router-wss
    ports:
      - 3023:3023
    networks:
      - ziticontrol
    volumes:
      - ziti-fs:/openziti
    entrypoint: /bin/bash
    command: "/openziti/run-edge-router.sh wss"

  ziti-fabric-router-br:
    image: openziti/ziti-quickstart
    environment:
      - ZITI_EDGE_ROUTER_RAWNAME=ziti-fabric-router-br
    ports:
      - 3024:3022
    networks:
      - ziticontrol
      - zitiblue
      - zitired
    volumes:
      - ziti-fs:/openziti
    entrypoint: /bin/bash
    command: "/openziti/run-edge-router.sh fabric"

networks:
  ziticontrol:
  zitired:
  zitiblue:

volumes:
  ziti-fs:

