version: '2.4'
services:
  ziti-controller:
    image: openziti/ziti-quickstart
    env_file:
      - ./default.env
    build: ./image
    ports:
      - 1280:1280
    networks:
      ziticontrol:
        aliases:
          - ziti-controller
          - ziti-edge-controller
    volumes:
      - ziti-fs:/openziti
    entrypoint:
      - /openziti/run-controller.sh

  ziti-edge-router:
    image: openziti/ziti-quickstart
    environment:
      - ZITI_EDGE_ROUTER_RAWNAME=ziti-edge-router
    depends_on:
      ziti-controller:
        condition: service_started
    ports:
      - 3022:3022
    networks:
      ziticontrol:
        aliases:
          - ziti-edge-router
    volumes:
      - ziti-fs:/openziti
    entrypoint:
      - /openziti/run-edge-router.sh

  ziti-edge-router-wss:
    image: openziti/ziti-quickstart
    environment:
      - ZITI_EDGE_ROUTER_RAWNAME=ziti-edge-router-wss
    depends_on:
      ziti-controller:
        condition: service_started
    ports:
      - 3023:3022
    networks:
      ziticontrol:
        aliases:
          - ziti-edge-router
    volumes:
      - ziti-fs:/openziti
    entrypoint: /bin/bash
    command: "/openziti/run-edge-router.sh wss"
networks:
  ziticontrol:
  zitired:
  zitiblue:

volumes:
  ziti-fs:

