version: '2.4'
services:
  ziti-controller:
    image: openziti/quickstart:latest
    env_file:
      - ./default.env
    ports:
      - "1280:1280"
    networks:
      zitiblue:
        aliases:
          - ziti-edge-controller
      zitired:
        aliases:
          - ziti-edge-controller
    volumes:
      - ziti-fs:/openziti
    entrypoint:
      - "/openziti/scripts/run-controller.sh"

  ziti-edge-router:
    image: openziti/quickstart:latest
    environment:
      - ZITI_EDGE_ROUTER_RAWNAME=ziti-edge-router
    ports:
      - "3022:3022"
    networks:
      - zitiblue
      - zitired
    volumes:
      - ziti-fs:/openziti
    entrypoint: /bin/bash
    command: "/openziti/scripts/run-edge-router.sh edge"

networks:
  zitired:
  zitiblue:

volumes:
  ziti-fs:

