run:
  deadline: 8m
  skip-dirs:
    - controller/zitiql

# golangci gives false positives for implementations of methods using generics in generic interfaces
issues:
  exclude-rules:
    - path: 'controller/model/.*.go'
      linters:
        - unused
