version: "~> 1.0"

import:
  - source: netfoundry/ziti-ci:ziti-go-defaults.yml@v1
  - source: buildinfo.yml
    if: branch != update-dependency

env:
  global:
    - GOX_OUTPUT="release/{{.Arch}}/{{.OS}}/{{.Dir}}"

matrix:
  include:
    - os: linux
      arch: amd64
      env: GOX_OS=linux
    - os: linux
      arch: arm64
      env: GOX_OS=linux
    - os: mac
      env: GOX_OS=darwin
    - os: windows
      env: GOX_OS=windows

script:
  - go get github.com/mitchellh/gox
  - CGO_ENABLED=true gox -os="$GOX_OS" -arch=$TRAVIS_CPU_ARCH -output=$GOX_OUTPUT ./...