version: "3.3"

x-base-service-conf: &base-service-conf
    image: netfoundry/ziti-tunnel:latest
    volumes:
    - .:/netfoundry
    environment:
        - NF_REG_NAME
        - PFXLOG_NO_JSON=true
​
services:
    ziti-test:
        <<: *base-service-conf
        network_mode: host
        entrypoint: ["sh", "-c", "while true; do sleep 11; done"]
    ziti-tproxy:
        <<: *base-service-conf
        network_mode: host
        cap_add:
        - NET_ADMIN    # iptables filter
        - NET_RAW      # iptables mangle
        command: tproxy
#        command: tproxy --resolver udp://127.0.0.123:53
    ziti-iproxy:
        <<: *base-service-conf
        network_mode: host
        cap_add:
        - NET_ADMIN    # iptables filter
        - NET_RAW      # iptables mangle
        command: tproxy --resolver none
    ziti-proxy:
        <<: *base-service-conf
        ports:
        - "8888:8888"
        - "9999:9999"
        command: proxy "my example service":8888 "my other example service":9999
    ziti-host-docker:  # terminate a service for a server that's reachable by this docker network
        <<: *base-service-conf
        command: host 
    ziti-host-egress:  # terminate a service for a server that's reachable by the host network
        <<: *base-service-conf
        network_mode: host
        command: host 
